/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iu.kmi.layout;

import com.iu.kmi.database.repository.RepositoryProxy;
import com.iu.kmi.entities.Kondition;
import com.iu.kmi.layout.models.AngebotKonditionModel;
import com.iu.kmi.repositories.KonditionRepository;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author adrian
 */
public class AngebotKonditionPopup extends javax.swing.JFrame {

    private AngebotInterface parent;
    private KonditionRepository konditionRepository;
    private List<Kondition> konditionList;
    private List<Kondition> createdKonditionList;
    private List<Kondition> updatedKonditionList;

    /**
     * Creates new form AngebotKonditionPopup
     */
    public AngebotKonditionPopup(AngebotInterface parent) throws ReflectiveOperationException, SQLException {
        initComponents();
        this.parent = parent;
        this.konditionRepository = RepositoryProxy.newInstance(KonditionRepository.class);
        this.load();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                parent.onKonditionPopupClosed();
            }
        });
    }

    private void load() throws ReflectiveOperationException, SQLException {
        this.konditionList = this.konditionRepository.findAll().execute();
        jComboBox1.removeAllItems();
        jComboBox1.addItem(new AngebotKonditionModel(null, true));
        konditionList.forEach(kondition -> jComboBox1.addItem(new AngebotKonditionModel(kondition, false)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_name = new javax.swing.JTextField();
        text_zahlung = new javax.swing.JTextField();
        text_liefer = new javax.swing.JTextField();
        text_rabatt = new javax.swing.JTextField();
        button_new = new javax.swing.JButton();
        button_speichern = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Konditionen");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Kondition");

        jLabel3.setText("Name");

        jLabel4.setText("Zahlungsbedingung");

        jLabel5.setText("Lieferbedingungen");

        jLabel6.setText("Rabatt");

        text_name.setText("jTextField1");

        text_zahlung.setText("jTextField1");

        text_liefer.setText("jTextField1");

        text_rabatt.setText("jTextField1");

        button_new.setText("Neu");
        button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newActionPerformed(evt);
            }
        });

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });

        button_cancel.setText("Abbrechen");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_name, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(text_zahlung)
                            .addComponent(text_liefer)
                            .addComponent(text_rabatt))
                        .addGap(18, 18, 18)
                        .addComponent(button_new))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(button_speichern)
                        .addGap(26, 26, 26)
                        .addComponent(button_cancel)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_new))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_zahlung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_liefer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_rabatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_speichern)
                    .addComponent(button_cancel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newActionPerformed
        if(jComboBox1.getSelectedIndex() != 0) {
            return;
        }
        Kondition kondition = new Kondition();
        kondition.setKonditionNr("K" + (konditionList.size() + 1));
        kondition.setName(text_name.getText());
        kondition.setZahlungsbedingungen(text_zahlung.getText());
        kondition.setLieferbedingungen(text_liefer.getText());
        kondition.setRabatt(BigDecimal.valueOf(Double.parseDouble(text_rabatt.getText())));

        konditionRepository.insert(kondition);
        try {
            this.load();
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_button_newActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem() == null) {
            return;
        }
        Kondition selectedModel = ((AngebotKonditionModel) jComboBox1.getSelectedItem()).value;

        if (selectedModel == null) {
            text_name.setText("");
            text_zahlung.setText("");
            text_liefer.setText("");
            text_rabatt.setText("");
        } else {
            text_name.setText(selectedModel.getName());
            text_zahlung.setText(selectedModel.getZahlungsbedingungen());
            text_liefer.setText(selectedModel.getLieferbedingungen());
            text_rabatt.setText(String.valueOf(selectedModel.getRabatt()));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        Kondition selectedModel = ((AngebotKonditionModel) jComboBox1.getSelectedItem()).value;

        if (selectedModel == null) {
            return;
        }

        selectedModel.setName(text_name.getText());
        selectedModel.setZahlungsbedingungen(text_zahlung.getText());
        selectedModel.setLieferbedingungen(text_liefer.getText());
        selectedModel.setRabatt(BigDecimal.valueOf(Double.parseDouble(text_rabatt.getText())));

        konditionRepository.update(selectedModel);
        try {
            this.load();
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_button_speichernActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_new;
    private javax.swing.JButton button_speichern;
    private javax.swing.JComboBox<AngebotKonditionModel> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField text_liefer;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_rabatt;
    private javax.swing.JTextField text_zahlung;
    // End of variables declaration//GEN-END:variables
}
