/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iu.kmi.layout;
import com.iu.kmi.database.repository.RepositoryProxy;
import com.iu.kmi.entities.AuftragsPosition;
import com.iu.kmi.repositories.AuftragsPositionRepository;

/**
 *
 * @author testg
 */
public class AuftragsPositionInterface extends javax.swing.JFrame {

    /**
     * Creates new form AuftragsPositionInterface
     */
    public AuftragsPositionInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAuftragsPositionNummer = new javax.swing.JTextField();
        jTextFieldArtikelNummer = new javax.swing.JTextField();
        jButtonAbbrechen = new javax.swing.JButton();
        jButtonSpeichern = new javax.swing.JButton();
        jLabelTerminAuftragNummer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTerminAuftragsNummer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldAuftragsPositionNummer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextFieldAuftragsPositionNummer.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldAuftragsPositionNummer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAuftragsPositionNummer.setAutoscrolls(false);
        jTextFieldAuftragsPositionNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuftragsPositionNummerActionPerformed(evt);
            }
        });

        jTextFieldArtikelNummer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextFieldArtikelNummer.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldArtikelNummer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldArtikelNummer.setAutoscrolls(false);
        jTextFieldArtikelNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldArtikelNummerActionPerformed(evt);
            }
        });

        jButtonAbbrechen.setBackground(new java.awt.Color(244, 67, 54));
        jButtonAbbrechen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButtonAbbrechen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbbrechen.setText("Abbrechen");
        jButtonAbbrechen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButtonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbbrechenActionPerformed(evt);
            }
        });

        jButtonSpeichern.setBackground(new java.awt.Color(58, 132, 233));
        jButtonSpeichern.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButtonSpeichern.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSpeichern.setText("Speichern");
        jButtonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeichernActionPerformed(evt);
            }
        });

        jLabelTerminAuftragNummer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelTerminAuftragNummer.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTerminAuftragNummer.setText("Terminauftragsnummer");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Auftragspositionsnummer");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Artikelnummer");

        jTextFieldTerminAuftragsNummer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextFieldTerminAuftragsNummer.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldTerminAuftragsNummer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTerminAuftragsNummer.setAutoscrolls(false);
        jTextFieldTerminAuftragsNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTerminAuftragsNummerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Auftragsposition");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAbbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTerminAuftragNummer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldArtikelNummer, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(jTextFieldAuftragsPositionNummer)
                    .addComponent(jTextFieldTerminAuftragsNummer))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAuftragsPositionNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldArtikelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTerminAuftragNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTerminAuftragsNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAuftragsPositionNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuftragsPositionNummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuftragsPositionNummerActionPerformed

    private void jTextFieldArtikelNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldArtikelNummerActionPerformed
        // bla
    }//GEN-LAST:event_jTextFieldArtikelNummerActionPerformed

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        jTextFieldAuftragsPositionNummer.setText("");
        jTextFieldArtikelNummer.setText("");
        jTextFieldTerminAuftragsNummer.setText("");
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeichernActionPerformed
        if(jTextFieldAuftragsPositionNummer.getText().isEmpty() || jTextFieldArtikelNummer.getText().isEmpty() || jTextFieldTerminAuftragsNummer.getText().isEmpty()){
            //do nothing
        }else{
        AuftragsPosition auftragsposition = new AuftragsPosition();
        //auftragsposition.setArtikelNr(jTextFieldTerminAuftragsNummer.getText());
        auftragsposition.setArtikelNr(jTextFieldArtikelNummer.getText());
        auftragsposition.setAuftragspositionNr(jTextFieldAuftragsPositionNummer.getText());
        auftragsposition.setTerminauftragNr(jTextFieldTerminAuftragsNummer.getText());
        //auftragsposition.setEinzelpreis(Double.parseDouble(jTextFieldArtikelpreis.getText()));
        //auftragsposition.setLieferdatum(bla);
        AuftragsPositionRepository auftrPositionRepo = RepositoryProxy.newInstance(AuftragsPositionRepository.class);
        auftrPositionRepo.insert(auftragsposition);
        }
    }//GEN-LAST:event_jButtonSpeichernActionPerformed

    private void jTextFieldTerminAuftragsNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTerminAuftragsNummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTerminAuftragsNummerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuftragsPositionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuftragsPositionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuftragsPositionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuftragsPositionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuftragsPositionInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbbrechen;
    private javax.swing.JButton jButtonSpeichern;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTerminAuftragNummer;
    private javax.swing.JTextField jTextFieldArtikelNummer;
    private javax.swing.JTextField jTextFieldAuftragsPositionNummer;
    private javax.swing.JTextField jTextFieldTerminAuftragsNummer;
    // End of variables declaration//GEN-END:variables
}
