/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iu.kmi.layout;

import com.iu.kmi.database.repository.Repository;
import com.iu.kmi.database.repository.RepositoryProxy;
import com.iu.kmi.entities.Kundenauftrag;
import com.iu.kmi.repositories.KundenauftragRepository;

/**
 *
 * @author Julian
 */
public class KundenauftragInterface extends javax.swing.JFrame {

    /**
     * Creates new form KundenauftragInterface
     */
    public KundenauftragInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitelKundenauftrag = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        auftragsTypComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        anschriftTextField = new javax.swing.JTextField();
        kundenNummerTextField = new javax.swing.JTextField();
        kundenNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nrTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        angebotsDatumTextField = new javax.swing.JTextField();
        zahlungsBedingungTextField = new javax.swing.JTextField();
        lieferbedingungTextField = new javax.swing.JTextField();
        lieferTerminTextField = new javax.swing.JTextField();
        gultigkeitAngebotTextField = new javax.swing.JTextField();
        jButtonKundendatenSuchen = new javax.swing.JButton();
        jButtonBearbeiten = new javax.swing.JButton();
        jButtonAbbrechen = new javax.swing.JButton();
        jButtonSpeichern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelTitelKundenauftrag.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelTitelKundenauftrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitelKundenauftrag.setText("Kundenauftrag");
        jPanel1.add(jLabelTitelKundenauftrag, java.awt.BorderLayout.PAGE_START);

        auftragsTypComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terminauftrag (TA)", "Planauftrag (PA)" }));
        auftragsTypComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auftragsTypComboBoxActionPerformed(evt);
            }
        });
        jDesktopPane1.add(auftragsTypComboBox);
        auftragsTypComboBox.setBounds(200, 170, 170, 22);

        jLabel2.setText("Anschrift");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(30, 130, 110, 16);

        jLabel3.setText("Kundennummer");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(30, 50, 110, 16);

        jLabel4.setText("Kundenname");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(30, 90, 110, 16);

        anschriftTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anschriftTextFieldActionPerformed(evt);
            }
        });
        jDesktopPane1.add(anschriftTextField);
        anschriftTextField.setBounds(200, 130, 260, 22);

        kundenNummerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kundenNummerTextFieldActionPerformed(evt);
            }
        });
        jDesktopPane1.add(kundenNummerTextField);
        kundenNummerTextField.setBounds(200, 50, 110, 22);
        jDesktopPane1.add(kundenNameTextField);
        kundenNameTextField.setBounds(200, 90, 110, 22);

        jLabel5.setText("Nr.");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(650, 20, 46, 16);

        nrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrTextFieldActionPerformed(evt);
            }
        });
        jDesktopPane1.add(nrTextField);
        nrTextField.setBounds(680, 20, 80, 22);

        jLabel6.setText("Angebotsdatum");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(30, 370, 110, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "Art.- Nr.", "Artikelname", "Menge"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 510, 720, 210);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setText("Anfrageposition");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(30, 460, 180, 18);

        jLabel8.setText("Auftragstyp");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(30, 170, 110, 16);

        jLabel9.setText("Zahlungsbedingung");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(30, 210, 140, 16);

        jLabel10.setText("Lieferbedingung");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(30, 250, 110, 16);

        jLabel11.setText("Liefertermin");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(30, 290, 110, 16);

        jLabel12.setText("Gültigkeit des Angebots");
        jDesktopPane1.add(jLabel12);
        jLabel12.setBounds(30, 330, 170, 16);
        jDesktopPane1.add(angebotsDatumTextField);
        angebotsDatumTextField.setBounds(200, 370, 64, 22);
        jDesktopPane1.add(zahlungsBedingungTextField);
        zahlungsBedingungTextField.setBounds(200, 210, 64, 22);
        jDesktopPane1.add(lieferbedingungTextField);
        lieferbedingungTextField.setBounds(200, 250, 64, 22);
        jDesktopPane1.add(lieferTerminTextField);
        lieferTerminTextField.setBounds(200, 290, 64, 22);
        jDesktopPane1.add(gultigkeitAngebotTextField);
        gultigkeitAngebotTextField.setBounds(200, 330, 64, 22);

        jButtonKundendatenSuchen.setText("Kundendaten suchen");
        jButtonKundendatenSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKundendatenSuchenActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonKundendatenSuchen);
        jButtonKundendatenSuchen.setBounds(40, 730, 180, 23);

        jButtonBearbeiten.setText("Bearbeiten");
        jButtonBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBearbeitenActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonBearbeiten);
        jButtonBearbeiten.setBounds(270, 730, 110, 23);

        jButtonAbbrechen.setText("Abbrechen");
        jButtonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbbrechenActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAbbrechen);
        jButtonAbbrechen.setBounds(430, 730, 100, 23);

        jButtonSpeichern.setText("Speichern");
        jButtonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeichernActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonSpeichern);
        jButtonSpeichern.setBounds(593, 730, 120, 23);

        jScrollPane1.setViewportView(jDesktopPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void auftragsTypComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auftragsTypComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auftragsTypComboBoxActionPerformed

    private void anschriftTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anschriftTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anschriftTextFieldActionPerformed

    private void kundenNummerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kundenNummerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kundenNummerTextFieldActionPerformed

    private void nrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrTextFieldActionPerformed

    private void jButtonKundendatenSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKundendatenSuchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKundendatenSuchenActionPerformed

    private void jButtonBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBearbeitenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBearbeitenActionPerformed

    private void emptyAllJTextFields(){
        angebotsDatumTextField.setText("");
        anschriftTextField.setText("");
        kundenNameTextField.setText("");
        kundenNummerTextField.setText("");
        lieferTerminTextField.setText("");
        lieferbedingungTextField.setText("");
        gultigkeitAngebotTextField.setText("");
        nrTextField.setText("");
        zahlungsBedingungTextField.setText("");
        auftragsTypComboBox.setSelectedIndex(0);
    }
    
    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        emptyAllJTextFields();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeichernActionPerformed
        // abspeichern eines Debitors
        Kundenauftrag auftrag = new Kundenauftrag(kundenNummerTextField.getText(), kundenNummerTextField.getText(), lieferTerminTextField.getText(), lieferbedingungTextField.getText(), "", "");
        KundenauftragRepository kundenRepo = RepositoryProxy.newInstance(KundenauftragRepository.class);
        kundenRepo.insert(auftrag);
        emptyAllJTextFields();
    }//GEN-LAST:event_jButtonSpeichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LagerbestandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LagerbestandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LagerbestandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LagerbestandInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KundenauftragInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angebotsDatumTextField;
    private javax.swing.JTextField anschriftTextField;
    private javax.swing.JComboBox<String> auftragsTypComboBox;
    private javax.swing.JTextField gultigkeitAngebotTextField;
    private javax.swing.JButton jButtonAbbrechen;
    private javax.swing.JButton jButtonBearbeiten;
    private javax.swing.JButton jButtonKundendatenSuchen;
    private javax.swing.JButton jButtonSpeichern;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitelKundenauftrag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kundenNameTextField;
    private javax.swing.JTextField kundenNummerTextField;
    private javax.swing.JTextField lieferTerminTextField;
    private javax.swing.JTextField lieferbedingungTextField;
    private javax.swing.JTextField nrTextField;
    private javax.swing.JTextField zahlungsBedingungTextField;
    // End of variables declaration//GEN-END:variables
}
