/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iu.kmi.layout;
import javax.swing.JOptionPane;
import com.iu.kmi.entities.OffenerPosten;
import com.iu.kmi.entities.Rechnung;
import com.iu.kmi.repositories.RechnungRepository;
import com.iu.kmi.repositories.OffenerPostenRepository;
import com.iu.kmi.database.repository.RepositoryProxy;
import com.iu.kmi.entities.Zahlung;
import com.iu.kmi.repositories.ZahlungRepository;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Tim
 */
public class ZahlungInterface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public ZahlungInterface() {
        initComponents();
    }
    ZahlungRepository zahlungRepository = RepositoryProxy.newInstance(ZahlungRepository.class);
    RechnungRepository rechnungRepository = RepositoryProxy.newInstance(RechnungRepository.class);
    OffenerPostenRepository opRepository = RepositoryProxy.newInstance(OffenerPostenRepository.class);
    Rechnung rechnung;
    OffenerPosten op;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Auftragsnr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Betrag = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        speichern = new javax.swing.JButton();
        abbrechen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        zahlungsnr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Auftragsnr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Auftragsnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuftragsnrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Rechnungsnummer");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Betrag");

        Betrag.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Betrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BetragActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Zahlungseingang");

        speichern.setBackground(new java.awt.Color(58, 132, 233));
        speichern.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        speichern.setForeground(new java.awt.Color(255, 255, 255));
        speichern.setText("Speichern");
        speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speichernActionPerformed(evt);
            }
        });

        abbrechen.setBackground(new java.awt.Color(244, 67, 54));
        abbrechen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        abbrechen.setForeground(new java.awt.Color(255, 255, 255));
        abbrechen.setText("Abbrechen");
        abbrechen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Zahlungsnummer");

        zahlungsnr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        zahlungsnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zahlungsnrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(speichern, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(abbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zahlungsnr, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Betrag, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Auftragsnr, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Auftragsnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(zahlungsnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Betrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speichern, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuftragsnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuftragsnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuftragsnrActionPerformed

    private void BetragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BetragActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BetragActionPerformed

    private void speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speichernActionPerformed
        if (validateFields()) {
            BigDecimal betrag = convertBetragToFloat();
            if (betrag != null) {
                if (betrag.equals(0)) {
                    JOptionPane.showMessageDialog(this, "Der Betrag darf nicht 0 sein!", "Fehler", JOptionPane.ERROR_MESSAGE);
                    return; // Beendet die Methode, wenn der Betrag 0 ist
                }

                try {
                    // Prüfen ob die Rechnung existiert
                    rechnung = rechnungRepository.findById(Auftragsnr.getText()).findOne();
                    if (rechnung == null) {
                        JOptionPane.showMessageDialog(this, "Die Rechnung existiert nicht!", "Fehler", JOptionPane.ERROR_MESSAGE);
                        return; // Beendet die Methode, wenn die Rechnung nicht existiert
                    }

                    // Prüfen wie groß der Offene Posten ist
                    op = opRepository.findAll().where("rechnung_nr", Auftragsnr.getText()).findOne();
                    if (op.getGesamtbetrag().compareTo(betrag) == -1) {
                        JOptionPane.showMessageDialog(this, "Der Betrag übersteigt den Wert des offenen Posten!", "Fehler", JOptionPane.ERROR_MESSAGE);
                    } else {
                        op.setGesamtbetrag(op.getGesamtbetrag().subtract(betrag));
                        if (op.getGesamtbetrag().compareTo(BigDecimal.ZERO) == 1 && betrag.intValue() > 0) {
                            op.setStatus("teilgezahlt");
                        } else if (op.getGesamtbetrag().equals(BigDecimal.ZERO)) {
                            op.setStatus("bezahlt");
                        }

                        Zahlung zahlung = new Zahlung();
                        zahlung.setBetrag(betrag);
                        zahlung.setDebitor_nr(rechnung.getDebitor().getDebitor_nr());
                        zahlung.setOffener_posten_nr(op.getOffener_posten_nr());
                        zahlung.setZahlung_nr(zahlungsnr.getText());
                        zahlung.setZahlungsdatum(LocalDateTime.now());

                        zahlungRepository.insert(zahlung);
                        opRepository.update(op);
                    }
                } catch (ReflectiveOperationException | SQLException ex) {
                    Logger.getLogger(ZahlungInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

//GEN-LAST:event_speichernActionPerformed

    private void abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrechenActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_abbrechenActionPerformed

    private void zahlungsnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zahlungsnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zahlungsnrActionPerformed
    
    private boolean validateFields() {
    if (Auftragsnr.getText().trim().isEmpty() || 
        Betrag.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bitte füllen Sie alle Felder aus.", "Fehler", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}
    private BigDecimal convertBetragToFloat() {
    try {
        return new BigDecimal(Betrag.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Bitte geben Sie einen gültigen Betrag ein.", "Fehler", JOptionPane.ERROR_MESSAGE);
        return null;
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZahlungInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZahlungInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZahlungInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZahlungInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZahlungInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Auftragsnr;
    private javax.swing.JTextField Betrag;
    private javax.swing.JButton abbrechen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton speichern;
    private javax.swing.JTextField zahlungsnr;
    // End of variables declaration//GEN-END:variables
}
